# Generated by Django 2.1.5 on 2019-01-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categeroy',
            fields=[
                ('c_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=500)),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='productGallary')),
                ('catagory_name', models.ForeignKey(on_delete=True, to='APP.categeroy')),
            ],
        ),
    ]
