# Generated by Django 2.1.5 on 2019-01-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_signupimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_in', models.ImageField(upload_to='gallary')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterDetails',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('confirm_password', models.CharField(max_length=15)),
            ],
        ),
    ]
